version: "3"
services:
  marketmate-userService:
    container_name: marketmate-userService
    build: ./user-service
    image: userService-image
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/marketmate?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=tjdghks9471
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: tjdghks9471
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always
    networks:
      - network

  redis:
    image: redis:latest
    container_name: marketmate-redis
    ports:
      - "6379:6379"
    networks:
      - network

networks:
  network:
    driver: bridge
