version: "3"
services:
  databases1:
    image: mysql:latest
    container_name: mysql_marketmate
    hostname: localhost
    ports:
      - "3307:3306"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tjdghks9471
      MYSQL_DATABASE: marketmate
      MYSQL_USER: sunghwan
      MYSQL_PASSWORD: tjdghks9471
    restart: always
    networks:
      - app-tier

  database2:
    image: redis:latest
    container_name: marketmate-redis
    hostname: localhost
    ports:
      - "6379:6379"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
