version: "3"
services:
  databases1:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_marketmate
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      MYSQL_ROOT_PASSWORD: tjdghks9471
      MYSQL_DATABASE: marketmate
      MYSQL_USER: sunghwan
      MYSQL_PASSWORD: tjdghks9471
    restart: always

  database2:
    image: redis:latest
    container_name: marketmate-redis
    hostname: localhost
    ports:
      - "6379:6379"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge